name: rtc_opera
channels:
  - s1-etad
  - conda-forge
dependencies:
  - python>=3.10,<3.11
  - s1etad==0.5.3
  - s1etad_tools==0.8.1
  - rasterio==1.4.3
  - pip:
      - aioboto3==14.3.0
      - asf_search==8.3.4
      - docker==7.1.0
      - multiprocess==0.70.18
      - pyyaml==6.0.2
      - sentineleof==0.11.0
      - dem-handler @ git+https://github.com/GeoscienceAustralia/dem-handler.git